import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import JSONB, TSVECTOR
from sqlmodel import Field, SQLModel

# Footnotes are indexed at lower weight so body hits rank first but notes stay searchable.
_TSV = (
    "setweight(to_tsvector('{cfg}', coalesce(clean_text, '')), 'A') || "
    "setweight(to_tsvector('{cfg}', coalesce(footnotes, '')), 'B')"
)


class Page(SQLModel, table=True):
    """One PDF page. The source of truth for a book's text.

    Insert with Core (`insert(Page)`), not ORM objects: the tsv columns are
    generated by Postgres and must not appear in the INSERT.
    """

    __tablename__ = "pages"
    __table_args__ = (
        sa.UniqueConstraint("book_id", "page_number"),
        sa.Index("ix_pages_tsv", "tsv", postgresql_using="gin"),
        sa.Index("ix_pages_tsv_simple", "tsv_simple", postgresql_using="gin"),
    )

    id: int | None = Field(default=None, primary_key=True)
    book_id: int = Field(foreign_key="books.id", ondelete="CASCADE", index=True)
    # 1-based PDF page index (what the reader navigates by).
    page_number: int
    # Printed page label from the PDF, e.g. "xii" or "37", when the PDF defines one.
    label: str | None = None
    raw_text: str = Field(default="", sa_type=sa.Text)
    clean_text: str = Field(default="", sa_type=sa.Text)
    footnotes: str = Field(default="", sa_type=sa.Text)
    # Lines cleanup dropped, with the rule that dropped them: [{"text", "reason"}].
    removed_lines: list[dict] = Field(
        default_factory=list,
        sa_column=sa.Column(JSONB, nullable=False, server_default=sa.text("'[]'::jsonb")),
    )
    needs_ocr: bool = False
    is_ocr: bool = False
    # `english` stems (negation ~ negate); `simple` matches exact words.
    tsv: str | None = Field(
        default=None,
        sa_column=sa.Column(TSVECTOR, sa.Computed(_TSV.format(cfg="english"), persisted=True)),
    )
    tsv_simple: str | None = Field(
        default=None,
        sa_column=sa.Column(TSVECTOR, sa.Computed(_TSV.format(cfg="simple"), persisted=True)),
    )
